import '@/styles/index.css'

export const metadata = {
    title: 'Marketplace',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ru">
            <body>{children}</body>
        </html>
    )
}